# Generated by Django 4.1.4 on 2022-12-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageInstitute', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='id',
            field=models.SmallAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
